name: flexmerchandiser
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.5
  animate_do: ^2.1.0
  shared_preferences: ^2.2.2
  dio: ^5.4.2+1
  flutter_dotenv: ^5.1.0
  overlay_support: ^2.1.0
  http: ^1.2.0
  intl: ^0.19.0
  image_picker: ^1.0.8
  path: ^1.8.3
  flutter_spinkit: ^5.2.1
  fl_chart: ^0.67.0
  url_launcher: ^6.3.0
  top_snackbar_flutter: ^3.1.0
  syncfusion_flutter_charts: ^27.2.5
  lottie: ^3.3.1
  get: ^4.7.2
  bloc: ^8.1.4
  pin_code_fields: ^8.0.1
  google_fonts: ^6.1.0
  freezed_annotation: ^2.4.1
  confetti: ^0.7.0
  shimmer: ^2.0.0

  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.3.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^2.4.5
  json_serializable: ^6.7.1



flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/images/dashboardimages/
    - .env


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/flexpaylogo512.png"
  adaptive_icon_foreground: "assets/icon/flexpaylogo512.png"
  adaptive_icon_background: "#ffffff"